------------------------------------------------------------------

-- MSSQL QUERIES WİTH OPERATORS

-- ŞARTLI SELECT KOMUTU ÖRNEKLERİ

-- ADI ONUR VE SOYADI CAKILI OLAN KİŞİYİ GETİREN SORGUI
SELECT * FROM EMPLOYEES
WHERE NAME = 'ONUR' AND SURNAME = 'CAKILI'

-- İÇ İÇE SORGU ÖRNEĞİ
-- BU SORGU SADECE ÖRNEK OLMASI AÇISINDAN KULLANILMIŞTIR.
SELECT * FROM EMPLOYEES
WHERE NAME = 'ONUR' AND (SURNAME = 'CAKILI' AND CITY = 'ISTANBUL')

-- YAŞADIĞI ŞEHİR İSTANBUL İSE GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL'

-- YAŞADIĞI ŞEHİR İSTANBUL DEĞİLSE GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY <> 'ISTANBUL'

-- 20 YAŞINDAN KÜÇÜKLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE AGE < 20

-- 20 YAŞINDAN BÜYÜKLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE AGE > 20

-- 20 YAŞINDA VE 20 YAŞINDAN BÜYÜK OLANLARI GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE AGE >= 20

-- TARİH VE STRİNG İFADELERLE BİRLİKTE BÜYÜKTÜR, KÜÇÜKTÜR OPERATÖRLERİNİN KULLANIMI
-- ÖRNEKLER

SELECT * FROM EMPLOYEES
WHERE BIRTHDAY < '2000-12-05'

SELECT * FROM EMPLOYEES
WHERE BIRTHDAY > '2000-12-05'

SELECT * FROM EMPLOYEES
WHERE name > 'A'

SELECT * FROM EMPLOYEES
WHERE name < 'A'

-------

-- LIKE VE NOT LIKE OPERATÖRLERİ

-- LIKE OPERATORU İLE ADI 'ONUR' OLAN KİŞİYİ GETİREN SORGU 
SELECT * FROM EMPLOYEES
WHERE NAME LIKE 'ONUR'

-- LIKE OPERATORU İLE ADI 'A' İLE BAŞLAYAN KİŞİYİ GETİREN SORGU 
SELECT * FROM EMPLOYEES
WHERE NAME LIKE 'A%'

-- LIKE OPERATORU İLE ADI 'UR' İLE BİTEN KİŞİYİ GETİREN SORGU 
SELECT * FROM EMPLOYEES
WHERE NAME LIKE '%UR'

-- LIKE OPARTORU İLE ADI 'O' İLE BAŞLAMAYANLARI GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE NAME NOT LIKE 'O%'

-- LIKE OPARTORU İLE SOYADINDA 'M' İÇERENLERİ GETİR
SELECT * FROM EMPLOYEES
WHERE NAME LIKE '%M%'

--------
-- BETWEEN (ARASINDA) OPERATÖRÜ

-- YAŞI 0 VE 20 ARASINDA OLAN KİŞİLERİ GETİREN SORGU
-- 0 VE 20 DAHİLDİR
SELECT * FROM EMPLOYEES
WHERE AGE BETWEEN 0 AND 20

-- DOGUM TARİHLERİ '1990-01-01' VE '2000-01-01' ARASINDA OLAN KİŞİLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE BIRTHDAY BETWEEN '1990-01-01' AND '2000-01-01'

---
-- IN VE NOT IN OPERATÖRLERİ

-- ADINDA 'AHMET' VE 'MEHMET' OLANLARI GETİREN SORGU  
SELECT * FROM  EMPLOYEES
WHERE NAME IN ('AHMET', 'MEHMET')

-- ADINDA 'A' İÇERMEYENLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE NAME NOT IN ('A')
