------- DDL Komutları -------

-- 1) CREATE KOMUTU, BİR VERITABANI NESNESİ OLUŞTURMAK İÇİN KULLANILIR

-- DB OLUŞTURMAK
CREATE DATABASE TEST

-- TABLE OLUŞTURMAK
CREATE TABLE CUSTOMERS
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50),
  GENDER VARCHAR(1),
  BIRTHDATE DATE,
  CITY VARCHAR(50),
  TOWN VARCHAR(50),
  TELNR VARCHAR(50),
  TCNO VARCHAR(11)
)


-- 2) ALTER KOMUTU, BİR VERITABANI NESNESİ'NİN ÖZELLİKLERİNİ DEĞİŞTİRMEK İÇİN KULLANILIR

ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(20) 
-- ALTER KOMUTU İLE ID KOLONUNA PRIMARY KEY EKLEYEN SQL SORGUSU
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID)

-- ALTER KOMUTU İLE CUSTOMER TABLOSUNA AGE ALANINI EKLEYEN SQL SORGUSU
ALTER TABLE CUSTOMERS ADD AGE INT

-- ALTER KOMUTU İLE CUSTOMER TABLOSUNA AGEGROUP ALANINI EKLEYEN SQL SORGUSU
ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(20)

-- ALTER KOMUTU İLE NAME ALANINI NOT NULL YAPAN SQL SORGUSU
ALTER TABLE CUSTOMERS ALTER COLUMN NAME VARCHAR(50) NOT NULL

-- ALTER KOMUTU İLE GENDER ALANINI VARCHAR(10) YAPAN SQL SORGUSU
ALTER TABLE CUSTOMERS ALTER COLUMN GENDER VARCHAR(10)

-- ALTER KOMUTU İLE AGEGROUP ALANINI SİLEN SQL SORGUSU
ALTER TABLE CUSTOMERS DROP COLUMN AGEGROUP


-- 3) DROP KOMUTU, BİR VERITABANI NESNESİNİ TAMAMEN SİLMEK İÇİN KULLANILIR (NESNENİN KENDİSİNİ)

-- DELETE, TABLODAKİ VERİYİ SİLER VE ID SIFIRLAMAZ
-- TRUNCATE, TABLODAKİ VERİYİ SİLER VE ID SIFIRLAR
-- DROP, TABLONUN KENDİSİNİ TAMAMEN SİLER

DROP DATABASE TEST
DROP TABLE DEMO















