--- MSSQL DML Queries (101) ---

-- EMPLOYEES TABLOSUNU OLUŞTURAN CREATE SORGUSU -- 
CREATE TABLE EMPLOYEES
(
 ID INT IDENTITY PRIMARY KEY,
 TCNUMBER CHAR(11) NOT NULL,
 NAME VARCHAR(15) NOT NULL,
 SURNAME VARCHAR(15) NOT NULL,
 CITY VARCHAR(15),
 AGE INT,
 BIRTHDATE DATE,
 MONTHLYINCOME INT,
)


-- TABLONUN İÇERİSİNE DEĞER ATAYAN INSERT SORGUSU -- 
INSERT INTO EMPLOYEES(TCNUMBER, NAME, SURNAME, CITY, BIRTHDATE, MONTHLYINCOME)
VALUES ('12345678900','ONUR', 'CAKILI', 'ISTANBUL', '2000-01-01', 10000)

INSERT INTO EMPLOYEES(TCNUMBER, NAME, SURNAME, CITY, BIRTHDATE, MONTHLYINCOME)
VALUES ('12345678900','AHMET', 'MEHMET', 'ANKARA', '1995-12-20', 20000)

INSERT INTO EMPLOYEES(TCNUMBER, NAME, SURNAME, CITY, BIRTHDATE, MONTHLYINCOME)
VALUES ('12345678900','MEHMET', 'AHMET', 'KONYA', '1998-10-05', 30000)


-- TABLONUN TAMAMINI GETİREN SORGU -- 
SELECT * FROM EMPLOYEES

-- SADECE NAME VE SURNAME SÜTUNLARINI GETİREN SORGU -- 
SELECT NAME, SURNAME FROM EMPLOYEES

-- UPDATE KOMUTU İLE GİRİLEN ESKİ DEĞERİ YENİSİYLE GÜNCELLEMEK
-- ID'Sİ 3 OLAN KİŞİNİN TC KİMLİK NUMARASINI '11122233344' İLE DEĞİŞTİREN SORGU
UPDATE EMPLOYEES
SET TCNUMBER = '11122233344'
WHERE ID = 3

-- UPDATE KOMUTU İLE TÜM ÇALIŞANLARIN MAAŞINI +5.000 TL GÜNCELLEYEN SORGU -- 
UPDATE EMPLOYEES
SET MONTHLYINCOME = MONTHLYINCOME + 5000

-- UPDATE KOMUTU İLE PAZARLAMA DEPARTMANINDAKİ ÇALIŞANLARIN MAAŞINI +10.000 TL GÜNCELLEYEN SORGU 
-- UPDATE EMPLOYEES
-- SET MONTHLYINCOME = MONTHLYINCOME + 10.000
-- WHERE DEPARTMENT = 'PAZARLAMA'


-- DELETE, TRUNCATE KOMUTLARININ KULLANIMLARI

-- TABLO İÇERİSİNDEKİ VERİYİ TAMAMEN / KISMEN SİLMEK İÇİN DELETE KOMUTU KULLANILIR
-- TABLONUN İÇERİSİNDEKİ VERİYİ TAMAMEN SİLEN DELETE SORGUSU
DELETE FROM CUSTOMERS

-- TABLONUN İÇERİSİNDEKİ BELİRLİ BİR VERİYİ SİLMEK İÇİN DELETE SORGUSU
-- ADI = 'ONUR' OLAN KİŞİYİ TABLODAN SİLER
DELETE FROM CUSTOMERS
WHERE NAME = 'ONUR'

-- TRUNCATE İLE DELETE KOMUTLARI AYNI İŞLEVİ GÖRMEKTEDİR
-- DELETE İLE SİLME İŞLEMİ YAPILIRSA ID (PRİMARY KEY) KALDIĞI YERDEN DEVAM EDER
-- TRUNCATE İLE SİLME İŞLEMİ YAPILIRSA ID (PRİMARY KEY) SIFIRLANARAK DEVAM EDER
-- TRUNCATE KOMUTU, WHERE ŞART KOMUTUYLA BİRLİKTE KULLANILMAZ
TRUNCATE TABLE EMPLOYEES

--
--
-- DATEDIFF FONKSİYONU TARİHLER ARASINDA FARK ALMAK İÇİN KULLANILIR
-- SELECT DATEDIFF(interval, this, getdate())
SELECT DATEDIFF(YEAR, '1995-01-01', '2000-01-01')

-- GETDATE FONKSİYONU SİSTEM TARİHİNİ GETİREN FONKSİYONDUR
SELECT GETDATE()

-- ÇALIŞANLARIN YAŞINI HESAPLAYAN DATEDIFF SORGUSU
SELECT *, DATEDIFF(YEAR, BIRTHDAY, GETDATE()) FROM EMPLOYEES

-- TABLODAKİ SÜTUNU BAŞA SABİTLEMEK İÇİN KULLANILAN BİR YÖNTEM

-- MONTHLYINCOME SÜTUNU SONLARDA YER ALMASINA RAĞMEN EN BAŞTA GÖSTERİLECEK BU SORGU İLE
-- SELECT MONTHLYINCOME,* FROM EMPOLOYEES 

-- ÇALIŞANLARIN YAŞINI 'AGE' DEĞİŞKENİNE ATAYAN UPDATE SORGUSU
UPDATE EMPLOYEES
SET AGE = DATEDIFF(YEAR, BIRTHDAY, GETDATE())

-- ÇALIŞANLARIN YAŞINI 'NULL' OLARAK DEĞİŞTİREN UPDATE SORGUSU
UPDATE EMPLOYEES
SET AGE = NULL

----
----
-- a. Sipariş Teslim Süresi Hesaplama

SELECT 
    OrderID, 
    DATEDIFF(day, OrderDate, DeliveryDate) AS DeliveryDays
FROM Orders;


---

-- b. Müşteri Yaşını Hesaplama

SELECT 
    CustomerName, 
    DATEDIFF(year, BirthDate, GETDATE()) AS Age
FROM Customers;


----

-- c. Ürün Son Kullanma Tarihi Kontrolü

SELECT 
    ProductName, 
    DATEDIFF(day, GETDATE(), ExpiryDate) AS DaysUntilExpiry
FROM Products
WHERE DATEDIFF(day, GETDATE(), ExpiryDate) <= 30; -- 30 günden az kalanlar


-----












