--- SQL DİĞER ALIŞTIRMALAR --- 

-- GENDER alanını değiştirmek
UPDATE EMPLOYEES set GENDER = 'MALE'
WHERE GENDER = 'M'

UPDATE EMPLOYEES set GENDER = 'FEMALE'
WHERE GENDER = 'F'

-- YAŞ GRUPLAMAK
SELECT * FROM EMPLOYEES
WHERE AGE IN (10, 20, 30, 40, 50, 60)

-- YAŞ GRUPLARINI ATAMAK
UPDATE EMPLOYEES SET AGEGROUP = 'GENÇ'
WHERE AGE BETWEEN 10 AND 20 

UPDATE EMPLOYEES SET AGEGROUP = 'ORTA YAŞLI'
WHERE AGE BETWEEN 30 AND 40 

UPDATE EMPLOYEES SET AGEGROUP = 'YAŞLI'
WHERE AGE BETWEEN 40 AND 60

-------------------------------------
-------DELETE KOMUTU + WHERE---------

-- ID'Sİ 1 OLAN ÇALIŞANI SİLEN SORGU
DELETE FROM EMPLOYEES WHERE ID = 1

-- ADI X OLAN ÇALIŞANI SİLEN SORGU
DELETE FROM EMPLOYEES WHERE NAME = 'ONUR'

-- CITY ISTANBUL İSE SİLEN SORGU
DELETE FROM EMPLOYEES WHERE CITY = 'ISTANBUL'

-- AGE GROUP, 'ORTA YAŞLI' İSE SİLEN SORGU
DELETE FROM EMPLOYEES WHERE AGEGROUP = 'ORTA YAŞLI'

--------------------------------------------------
---------AND VE OR OPERATÖRLERİ KULLANIMI--------

-- İSTANBULDA YAŞAYAN VE CİNSİYETİ ERKEK OLAN KİŞİLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL' AND GENDER = 'MALE'

-- İSTANBULDA YAŞAYAN, İLÇESİ AVCILAR OLAN VE CİNSİYETİ ERKEK OLAN KİŞİLERİ GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL' 
AND TOWN = 'AVCILAR' 
AND GENDER = 'MALE'

-- İSTANBULDA YAŞAYAN VE TOWN 'MUDANYA' OLAN BİR KAYIDI GETİREN SORGU GİRMEK İSTERSEK
-- HATALI BİR GİRİŞ OLACAKTIR ÇÜNKÜ MUDANYA BURSA'NIN BİR İLÇESİDİR
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL'
AND TOWN = 'MUDANYA'

------- OR OPERATÖRÜ -------
-- ŞARTLARDAN EN AZ BİR TANESİNİ SAĞLIYORSA GİRİLEN KAYDI GETİRİR

-- ISTANBUL VEYA İZMİRDE YAŞAYAN ÇALIŞANLARI GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL' OR CITY = 'IZMIR'


---- AND VE OR OPERATÖRÜNÜN BİRLİKTE KULLANIMI -----

-- HATALI SORGU
-- BİR KİŞİ HEM ÜSKÜDAR HEM DE ATASEHİR İLÇESİNDE OLAMAYACAĞI İÇİN HATALI SORGUDUR
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL' 
AND TOWN = 'USKUDAR' AND TOWN = 'ATASEHIR'

-- OLMASI GEREKEN SORGU ŞU ŞEKİLDEDİR
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL'
AND
TOWN = 'USKUDAR' OR TOWN = 'ATASEHIR'

-- BİR DİĞER HATALI 'OR' OPERATÖRÜ
-- BU SORGU KAYIT GETİRMEYECEK GİBİ DÜŞÜNÜLSE DE ATASEHİRDE YAŞAYANLARIN KAYDINI GETİRECEKTİR
-- CÜNKÜ OR OPERATÖRÜ KENDİSİNDEN ÖNCE GELEN ŞARTLARI YOK SAYMAKTADIR
SELECT * FROM EMPLOYEES
WHERE CITY = 'IZMIR'
AND
TOWN = 'USKUDAR' OR TOWN = 'ATASEHIR'

-- BU SORGUNUN DOGRU KULLANIMI İSE ŞU ŞEKİLDE OLMALIDIR
-- OR KOMUTU PARANTEZ ICINE ALINIRSA KENDİSİNDEN ÖNCEKİ KAYITLARI YOK SAYAMAZ
SELECT * FROM EMPLOYEES
WHERE CITY = 'IZMIR'
AND
(TOWN = 'USKUDAR' OR TOWN = 'ATASEHIR')


----ALIŞTIRMALAR----

-- YAŞ HESAPLAYAN SORGU 
UPDATE EMPLOYEES
SET AGE = DATEDIFF(YEAR, BIRTHDAY, GETDATE())

-- BURSADA YAŞAYAN VE ERKEK CALISANLARI GETIREN SORGU 
SELECT * FROM EMPLOYEES
WHERE CITY = 'BURSA' AND GENDER = 'MALE'

-- ADI 'A' İLE BAŞLAYAN VE YAŞI 20 - 30 ARASINDA OLAN CALISANLARI GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE NAME LIKE 'A%'
AND AGE BETWEEN 20 AND 30

-- ISTANBULDA YASAYAN VE YAŞI 20-30 YA DA 50-60 ARALIGINDA OLAN CALISANLARI GETİREN SORGU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ISTANBUL'
AND
(AGE BETWEEN 20 AND 30 OR AGE BETWEEN 50 AND 60)
















