----- EXAMPLES -----

-- 1) EMPLOYEES TABLOSUNDAN KAÇ TANE TEKİL ŞEHİR OLDUĞUNU GETİREN SQL SORGUSU
SELECT DISTINCT CITY FROM EMPLOYEES

-- 2) EMPLOYEES TABLOSUNDAN İZMİR'İN KAÇ TANE İLÇESİNİ OLDUĞUNU GETİREN SQL SORGUSU
SELECT DISTINCT TOWN FROM EMPLOYEES
WHERE CITY = 'İZMİR'

-- 3) EMPLOYEES TABLS. AGE ALANI EKLEYIN VE BUNU BIRTHDAY'E GÖRE HESAPLAYAN SQL SORGUSU
UPDATE EMPLOYEES
SET AGE = DATEDIFF(year,BIRTHDATE, GETDATE())

-- 4) ANKARADA YAŞAYANLARIN YAŞ ÇEŞİTLİLİĞİNİ GETİREN SQL SORGUSU
SELECT DISTINCT AGE FROM EMPLOYEES
WHERE CITY = 'ANKARA'

---------------------------------------------------------------------------------------------------------------

-- 1) EMPLOYEES TABLOSUNDAKİ KAYITLARI ID ALANINA GÖRE KÜCÜKTEN BÜYÜĞE SIRALAYAN SQL SORGUSU
SELECT * FROM EMPLOYEES
ORDER BY ID

-- 2) EMPLOYEES TABLOSUNDAKİ KAYITLARI ID ALANINA GÖRE BÜYÜKTEN KÜÇÜĞE SIRALAYAN SQL SORGUSU
SELECT * FROM EMPLOYEES
ORDER BY ID DESC

-- 3) EMPLOYEES TABLOSUNDAKİ KAYITLARI AD VE SOYAD ALANINA GÖRE A'DAN Z'YE SIRALAYAN SQL SORGUSU
SELECT * FROM EMPLOYEES
ORDER BY FULLNAME 

-- 4) EMPLOYEES TABLOSUNDAKİ KAYITLARI İL VE İLÇEYE GÖRE SIRALAYAN SQL SORGUSU
SELECT * FROM EMPLOYEES
ORDER BY CITY, TOWN

-- 5) EMPLOYEES TABLOSUNDA ANKARA'DA YAŞAYANLARI YAŞINA GÖRE SIRALAYAN SQL SORGUSU
SELECT * FROM EMPLOYEES
WHERE CITY = 'ANKARA'
ORDER BY AGE

-- 6) EMPLOYEES TABLOSUNDA ANKARA'DA YAŞAYANLARI DOĞUM TARİHLERİNE GÖRE SIRALAYAN SQL SORGUSU 
SELECT * FROM EMPLOYEES
WHERE CITY = 'ANKARA'
ORDER BY BIRTHDATE

-- 7) EMPLOYEES TABLOSUNDA İSTANBUL'DA YAŞAYANLARI ALIAS KULLANARAK 
	 --TÜRKÇE KOLON İSİMLERİ YAZDIRAN, İLÇE VE YAŞA GÖRE SIRALAYAN SQL SORGUSU
   
SELECT 
CITY AS İL,
TOWN AS İLÇE,
AGE AS YAŞ FROM EMPLOYEES
WHERE CITY = 'ISTANBUL' 
ORDER BY TOWN, AGE

--------------------------------------------------------------------------------------------------------

-- 1) EMPLOYEES TABLOSUNDA EN YAŞLI 10 KİŞİYİ GETİREN SQL SORGUSU
SELECT TOP 10 * FROM EMPLOYEES
ORDER BY BIRTHDATE

-- 2) EMPLOYEES TABLOSUNDA EN GENÇ 10 KİŞİYİ GETİREN SQL SORGUSU 
SELECT TOP 10 * FROM EMPLOYEES
ORDER BY BIRTHDATE DESC

-- 3) EMPLOYEES TABLOSUNDA KADINLAR ARASINDAN EN GENÇ 10 KİŞİYİ GETİREN SQL SORGUSU 
SELECT TOP 10 * FROM EMPLOYEES
WHERE GENDER = 'FEMALE'
ORDER BY BIRTHDATE DESC

-- 4) EMPLOYEES TABLOSUNDA ERKEKLER ARASINDAN EN YAŞLI %10'LUK KISMI GETİREN SQL SORGUSU
SELECT TOP 10 PERCENT * FROM EMPLOYEES
WHERE GENDER = 'MALE'
ORDER BY BIRTHDATE

-- 5) EMPLOYEES TABLOSUNDA ERKEKLER ARASINDAN ADI 'A' İLE BAŞLAYAN İLK 5 KİŞİYİ GETİREN SQL SORGUSU 
SELECT TOP 5 * FROM EMPLOYEES
WHERE 
GENDER = 'MALE'
AND
FULLNAME LIKE 'A%'




