-------- DDL ALISTIRMALAR BOLUMU --------


-- CREATE KOMUTU KULLANARAK 'TEST' ISIMLI DATABASE'I OLUSTURAN SQL SORGUSUNU YAZINIZ
CREATE DATABASE TEST


-- TEST DB'NIN ALTINA 'CUSTOMERS' ISIMLI TABLE'I OLUSTURAN SQL SORGUSUNU YAZINIZ
CREATE TABLE CUSTOMERS
(
  ID INT IDENTITY,
  NAMESURNAME VARCHAR(50),
  GENDER VARCHAR(1),
  BIRTHDATE DATE,
  CITY VARCHAR(50),
  TOWN VARCHAR(50),
  PHNUMBER VARCHAR(15),
  TCNUMBER VARCHAR(11)
)


-- OLUSTURULAN TABLONUN ID KISMINI PRIMARY KEY OLARAK GUNCELLEYEN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID)

-- NAMESURNAME ALANINI NVARCHAR(50) VE NOT NULL OLARAK DEĞİŞTİREN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ALTER COLUMN NAMESURNAME NVARCHAR(50) NOT NULL

-- CUSTOMERS TABLOSUNA AGE (INT) İSİMLİ ALAN EKLEYEN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ADD AGE INT

-- TABLOYA EKLEDİGİNİZ AGE ALANINI TINYINT OLARAK DEGİSTİREN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ALTER COLUMN AGE TINYINT

-- TABLOYA AGEGROUP VARCHAR(20) İSİMLİ BİR ALAN EKLEYEN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(20)

---
---
--- CUSTOMERS TABLOSUNA ID2 İSİMLİ OTOMATİK ARTAN (IDENTITY) ALAN EKLEYEN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS ADD ID2 INT IDENTITY(1,1)  -- TABLODA ZATEN BİR IDENTITY ALAN OLDUĞU İÇİN 2. ALANI EKLENMEMEKTEDİR

-- CUSTOMERS TABLOSUNDAN AGE VE AGEGROUP ALANLARINI KALDIRAN SQL SORGUSUNU YAZINIZ
ALTER TABLE CUSTOMERS DROP COLUMN AGE, AGEGROUP

-- CUSTOMERS TABLOSUNA INSERT İLE 1 SATIRLIK VERİ GİRİŞİ YAPINIZ 
-- GEREKLİ DİGER SİLME KOMUTLARINI GİREREK KONTROLLERİ SAGLAYINIZ
INSERT INTO CUSTOMERS (namesurname, gender, birthdate, city, town)
VALUES ('ONUR CAKILI', 'M', '2000-01-01', 'ISTANBUL', 'CEKMEKOY' )
-- SQL DEFAULT DATE TIME > YYYY/MM/DDD

SELECT * FROM CUSTOMERS

-- TRUNCATE İLE TABLOYU SİLİN VE TEKRAR INSERT İLE VERİ EKLEYEREK KONTROLUNU SAGLAYIN
TRUNCATE TABLE CUSTOMERS -- ID 1'DEN BAŞLADI

-- DELETE İLE TABLOYU SİLİN VE TEKRAR INSERT İLE VERİ EKLEYEREK KONTROLUNU SAGLAYIN
DELETE CUSTOMERS -- ID 2'DEN BAŞLADI 

-- DROP İLE TABLOYU SİLİN VE TEKRAR INSERT İLE VERİ EKLEYEREK KONTROLUNU SAGLAYIN
DROP TABLE CUSTOMERS -- TABLO TAMAMEN SİLİNDİ












